name: Check API Flow

on:
  push:
    branches:
      - '**'

jobs:
  check-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test login/register/authorization
        run: |
          set -e  # Exit on error

          BASE_URL="http://kthreljin.dyndns.biz:8080"
          USERNAME="ci-test-user"
          PASSWORD="ci-test-pass"

          echo "Registering user..."
          status=$(curl -s -o /dev/null -w "%{http_code}" -X POST "$BASE_URL/register" \
            -H "Content-Type: application/json" \
            -d "{\"username\": \"$USERNAME\", \"password\": \"$PASSWORD\"}")

          if [[ "$status" != "201" && "$status" != "409" ]]; then
            echo "/register returned $status"
            exit 1
          fi

          echo "Logging in..."
          LOGIN_RESPONSE=$(curl -s -X POST "$BASE_URL/login" \
            -H "Content-Type: application/json" \
            -d "{\"username\": \"$USERNAME\", \"password\": \"$PASSWORD\"}")

          ACCESS_TOKEN=$(echo "$LOGIN_RESPONSE" | jq -r '.access_token')
          REFRESH_TOKEN=$(echo "$LOGIN_RESPONSE" | jq -r '.refresh_token')

          if [ "$ACCESS_TOKEN" = "null" ] || [ -z "$ACCESS_TOKEN" ]; then
            echo "Failed to retrieve access token"
            echo "$LOGIN_RESPONSE"
            exit 1
          fi

          echo "Got access token"

          echo "Accessing /protected endpoint..."
          PROTECTED_STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Authorization: Bearer $ACCESS_TOKEN" \
            "$BASE_URL/protected")

          if [ "$PROTECTED_STATUS" != "200" ]; then
            echo "/protected returned $PROTECTED_STATUS"
            exit 1
          fi

          echo "Accessing /refresh endpoint..."
          REFRESH_STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Content-Type: application/json" \
            -d "{\"refresh_token\": \"$REFRESH_TOKEN\"}")

          if [ "$REFRESH_STATUS" != "200" ]; then
            echo "/refresh returned $REFRESH_STATUS"
            exit 1
          fi

          echo "All endpoint checks passed"
